app:
  logFile: log/gin.log
  processLogFile: log/process.log
  httpPort: 8080
  webSocketPort: 8089
  rpcPort: 9001
  httpUrl: 10.42.1.70:8080
  webSocketUrl: 10.42.1.70:8089

redis:
  addr: "localhost:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConns: 30
